args = {
    'data_dir': 'data/',
    'labeled_filename': 'train.pkl',
    'pred_filename': 'test.pkl',
    'seed': 647,
    'val_size': 0.1,
    'model_type': 'bert-base-uncased',
    'do_lower_case': True,
    'max_seq_length_fsent': 128,
    'max_seq_length_pair': 256,
    'target_ratio': 0.5,
    'num_train_samples_fsent': int(1e4),
    'num_train_samples_pair': int(1e4),
    'num_val_samples_fsent': int(1e3),
    'num_val_samples_pair': int(1e3),
    'num_epochs_fsent': 5,
    'num_epochs_pair': 10,
    'train_batch_size_fsent': 16,
    'train_batch_size_pair': 16,
    'val_batch_size_fsent': 16,
    'val_batch_size_pair': 16,
    'lr_fsent': 5e-5,
    'lr_pair': 5e-5,
    'adam_eps_fsent': 1e-8,
    'adam_eps_pair': 1e-8,
    'warmup_steps_fsent': 0,
    'warmup_steps_pair': 0
}
